/* Generated By:JavaCC: Do not edit this line. SuggestionParserConstants.java */
package lessonMapper.diffusion.suggestion;

/**
 * 
 */
public interface SuggestionParserConstants {

  /**
   * 
   */
  int EOF = 0;
  
  /**
   * 
   */
  int max = 5;
  
  /**
   * 
   */
  int min = 6;
  
  /**
   * 
   */
  int union = 7;
  
  /**
   * 
   */
  int inter = 8;
  
  /**
   * 
   */
  int sum = 9;
  
  /**
   * 
   */
  int div = 10;
  
  /**
   * 
   */
  int prod = 11;
  
  /**
   * 
   */
  int sub = 12;
  
  /**
   * 
   */
  int MAX = 13;
  
  /**
   * 
   */
  int MIN = 14;
  
  /**
   * 
   */
  int UNION = 15;
  
  /**
   * 
   */
  int INTER = 16;
  
  /**
   * 
   */
  int SUM = 17;
  
  /**
   * 
   */
  int DIV = 18;
  
  /**
   * 
   */
  int PROD = 19;
  
  /**
   * 
   */
  int SUB = 20;
  
  /**
   * 
   */
  int VI = 21;
  
  /**
   * 
   */
  int LI = 22;
  
  /**
   * 
   */
  int eq = 23;
  
  /**
   * 
   */
  int inf = 24;
  
  /**
   * 
   */
  int inf_eq = 25;
  
  /**
   * 
   */
  int sup = 26;
  
  /**
   * 
   */
  int sup_eq = 27;
  
  /**
   * 
   */
  int dif = 28;
  
  /**
   * 
   */
  int contains = 29;
  
  /**
   * 
   */
  int contained = 30;
  
  /**
   * 
   */
  int OR = 31;
  
  /**
   * 
   */
  int AND = 32;
  
  /**
   * 
   */
  int STRING = 33;
  
  /**
   * 
   */
  int ATT_ID = 34;
  
  /**
   * 
   */
  int NUM = 35;

  /**
   * 
   */
  int DEFAULT = 0;

  /**
   * 
   */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"max\"",
    "\"min\"",
    "\"union\"",
    "\"intersection\"",
    "\"+\"",
    "\"/\"",
    "\"*\"",
    "\"-\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"UNION\"",
    "\"INTERSECTION\"",
    "\"SUM\"",
    "\"DIVISION\"",
    "\"PRODUCT\"",
    "\"SUBTRACTION\"",
    "\"vi\"",
    "\"li\"",
    "\"=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"contains\"",
    "\"contained\"",
    "\"or\"",
    "\"and\"",
    "<STRING>",
    "<ATT_ID>",
    "<NUM>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "\",\"",
    "\".\"",
  };

}
