/* Generated By:JavaCC: Do not edit this line. RestrictionParserConstants.java */
package lessonMapper.diffusion.restriction;

/**
 * 
 */
public interface RestrictionParserConstants {

  /**
   * 
   */
  int EOF = 0;
  
  /**
   * 
   */
  int max = 5;
  
  /**
   * 
   */
  int min = 6;
  
  /**
   * 
   */
  int union = 7;
  
  /**
   * 
   */
  int inter = 8;
  
  /**
   * 
   */
  int sum = 9;
  
  /**
   * 
   */
  int div = 10;
  
  /**
   * 
   */
  int prod = 11;
  
  /**
   * 
   */
  int sub = 12;
  
  /**
   * 
   */
  int MAX = 13;
  
  /**
   * 
   */
  int MIN = 14;
  
  /**
   * 
   */
  int UNION = 15;
  
  /**
   * 
   */
  int INTER = 16;
  
  /**
   * 
   */
  int SUM = 17;
  
  /**
   * 
   */
  int DIV = 18;
  
  /**
   * 
   */
  int PROD = 19;
  
  /**
   * 
   */
  int SUB = 20;
  
  /**
   * 
   */
  int OIJ = 21;
  
  /**
   * 
   */
  int VIJ = 22;
  
  /**
   * 
   */
  int LI = 23;
  
  /**
   * 
   */
  int eq = 24;
  
  /**
   * 
   */
  int inf = 25;
  
  /**
   * 
   */
  int inf_eq = 26;
  
  /**
   * 
   */
  int sup = 27;
  
  /**
   * 
   */
  int sup_eq = 28;
  
  /**
   * 
   */
  int dif = 29;
  
  /**
   * 
   */
  int contains = 30;
  
  /**
   * 
   */
  int contained = 31;
  
  /**
   * 
   */
  int OR = 32;
  
  /**
   * 
   */
  int AND = 33;
  
  /**
   * 
   */
  int STRING = 34;
  
  /**
   * 
   */
  int ATT_ID = 35;
  
  /**
   * 
   */
  int NUM = 36;
  
  /**
   * 
   */
  int EQ = 37;
  
  /**
   * 
   */
  int INF = 38;
  
  /**
   * 
   */
  int INF_EQ = 39;
  
  /**
   * 
   */
  int SUP = 40;
  
  /**
   * 
   */
  int SUP_EQ = 41;
  
  /**
   * 
   */
  int DIF = 42;
  
  /**
   * 
   */
  int CONTAINS = 43;
  
  /**
   * 
   */
  int CONTAINED = 44;

  /**
   * 
   */
  int DEFAULT = 0;

  /**
   * 
   */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"max\"",
    "\"min\"",
    "\"union\"",
    "\"intersection\"",
    "\"+\"",
    "\"/\"",
    "\"*\"",
    "\"-\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"UNION\"",
    "\"INTERSECTION\"",
    "\"SUM\"",
    "\"DIVISION\"",
    "\"PRODUCT\"",
    "\"SUBTRACTION\"",
    "\"oij\"",
    "\"vij\"",
    "\"li\"",
    "\"=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"contains\"",
    "\"contained\"",
    "\"or\"",
    "\"and\"",
    "<STRING>",
    "<ATT_ID>",
    "<NUM>",
    "\"\\\'=\\\'\"",
    "\"\\\'<\\\'\"",
    "\"\\\'<=\\\'\"",
    "\"\\\'>\\\'\"",
    "\"\\\'>=\\\'\"",
    "\"\\\'!=\\\'\"",
    "\"\\\'contains\\\'\"",
    "\"\\\'contained\\\'\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "\",\"",
    "\".\"",
  };

}
